imgwelcome/imgwelcome.py
Enhancement
Long server names will no longer ride off of the end of the image. They will be shortened with '...'
=> server name length enhancement

imgwelcome/imgwelcome.py
Changed `aiohttp.get` to use `aiohttp.ClientSession()`
=> Let's not be deprecated again

chatchart/chatchart.py
Added ability to specify target channels as argument; Specify target channel in plot title; Increased display number from top10 to top20; integrated Discord Dark Theme; Added standartized colors to the pie chart
=> Several improvements to ChatChart

pingtime/pingtime.py
Unused import, remove pass context
=> I love the shortcuts

away/away.py
Add multiple away response toggles based off discord status.
=> [Away] Discord Status based responses added

chatchart/chatchart.py
Sends a message when message history only contains bot content
=> [V3 Chatchart] Handle bot only content

chatchart/chatchart.py, tools/tools.py
🐒 okay so the listchannels command list all of the channels in the guild and the listguilds command lists the guild that the bot is in, sorted by usercount
=> Add listchannels and listguilds commands

tools/tools.py
Removes check for url and only uses activity name
=> [V3 Tools] Fix for url AttributeError in uinfo

tools/tools.py
command `uinfo` updated to now account for the different activity types
=> [V3 Tools] Account for activity types

dungeon/dungeon.py, partycrash/info.json, timezone/timezone.py, tools/tools.py
=> Fixed the permissions

rndstatus/rndstatus.py
Fixes types in help text and adds a check to the value.
=> [V3 RndStatus] [p]rndstatus type fixes

antiphoneclapper/antiphoneclapper.py, away/away.py, dungeon/dungeon.py, nolinks/nolinks.py, otherbot/otherbot.py, seen/seen.py, trickortreat/trickortreat.py
This *should* take care of everything
=> V3.0 + V3.1 compability

seen/__init__.py, seen/seen.py
Removes 3.0 compatibility
Improves Disk IO by writting to config every 60 seconds
Also listen to `on_typing`, `on_message_edit`, `on_reaction_remove`, `on_reaction_add`
=> [Seen] Improves DisK I/O for bots with larger server and member base

seen/__init__.py, seen/seen.py
So forgot when the bot is used in DM a user obj is returned which does not have guild attribute.... this fixes it
=> Fixes Console errors when bot is used in DM

blurplefy/blurplefy.py
Updated the anniversary, it’s now the 5th 🎉
=> Update the countdown for the 5th anninversary

trickortreat/trickortreat.py
=> Fixes ranges that do not fully contain the stated values

trickortreat/trickortreat.py
Change on_message from "trick or treat" in the full content of the message to "trick or treat" at the start of the message.
=> [TrickOrTreat] Change on_message listener for "trick or treat"

pressf/pressf.py
Fixed an error when the press f message is deleted
Fixed a bug where two press fs could be started and the second would error
Fixed a bug where a message from any channel could be used as the thing to pay respects to
=> Multiple changes

otherbot/otherbot.py
Could cache some of this on load as well, but this is a really cheap way to reduce the times interacting with config for now.
=> Avoid touching config as much.

wolfram/wolfram.py
- I used `params` kwarg in request method so that `aiohttp` handles url encoding on its own.
- I changed `Result__Step-by-step+solution` to `Step-by-step+solution` so that WolframAlpha API will work for different kind of problems - equations, limits, derivatives, etc.
- I added `pagify` since some solutions tend to be long
Different inputs I tested this with ([this site](https://www.wolframalpha.com/examples/pro-features/step-by-step-solutions/) is full of such examples):
- find the extrema of 3x^4 - 4x^3 - 12x^2 + 1
- limit of (x - 3) / (x^2 - 2x - 3) as x approaches 3
- derivative of x^4 + 9x^3 + 7x - 2
- x^2 + 5x + 6 = 0
- factor x^3+2x^2+x+2
- (1 + tan(x))/(1 - tan(x)) = (cos(x) + sin(x))/(cos(x) - sin(x))
- prove by induction (3n)! > 3^n (n!)^3 for n>0
- glucose + oxygen -> water + …
=> [Wolfram] Improve reliability of requests for step-by-step solutions

info.json
See [docs](https://docs.discord.red/en/latest/guide_publish_cogs.html#keys-common-to-both-repo-and-cog-info-json-case-sensitive) for more info
=> `author` key in repo's `info.json` needs to be a list

tools/info.json, tools/tools.py
Add support for multiple activities and omit nickname if there's none
=> [uinfo] Multiple activities

tools/info.json, tools/tools.py
Okay, yeah, finally got time to actually figure out wtf am I doing
=> Add [Artist - Title] to uinfo

rndstatus/rndstatus.py
Updates the botstats option to be less blocking for large amounts of users, as well as changes the status changing to a task versus a listener along with other minor improvements to all statuses
=> [rndstatus] update botstats and other minor improvements

rndstatus/rndstatus.py
Also removes the redundant time checks as it's now a loop.
=> Fix rndstatus cycling

hunting/hunting.py
Also some name handling simplification
*Not tested, written "on the go"*
=> [Hunting] Use users instead of members in lb

hunting/hunting.py
=> [Hunting] Fix reaction time in settings overview

hunting/hunting.py
*i should have tested it by myself*
Fixes incorrect display of bang reaction in settings overview again, but in another way: `On` instead of `Off` and vice versa
Global leaderboard is now actually works
=> [Hunting] fix my previous too PRs

luigipoker/luigipoker.py
Check to make sure channel and user are the same
=> [LuigiPoker] Check for same context

luigipoker/luigipoker.py
Warning: Made in browser and untested
=> Lower content

otherbot/__init__.py, otherbot/otherbot.py
Not sure if this is the best way of handling a cache, this is how i've done it for stuff like highlight etc.
- Adds a cache to avoid a lot of config calls.
=> [otherbot] Avoid a lot of config calls.

hunting/hunting.py
`5 Snake of stealing eyess` → `5 Snake of stealing eyes`
*Perhaps i should have been just make an fork for mine version*
=> [Hunting] add support of animals ending with s

otherbot/info.json, otherbot/otherbot.py
That PR includes everything that is from my [fork](https://github.com/PredaaA/aikaterna-cogs/tree/v3/otherbot) and being used for a while on a few bots already, only thing new is an embed setting.
=> [OtherBot] Online notifications, embeds, emojis
